name: Release

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Build executable
        run: |
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
          fi

          GOOS=${{ matrix.goos }} \
          GOARCH=${{ matrix.goarch }} \
          CGO_ENABLED=0 \
          go build -trimpath -ldflags="-s -w" -o dist/tradify-cli-${{ matrix.goos }}-${{ matrix.goarch }}${EXT} ./cmd 

      - name: Upload new asset to existing release
        run: |
          gh release upload ${{ github.ref_name }} dist/tradify-cli-${{ matrix.goos }}_${{ matrix.goarch }}* --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
