name: Release

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 \
            go build -trimpath -ldflags="-s -w" -o dist/tradify-cli-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd

      - name: Zip artifacts
        run: |
          cd dist
          for f in *; do
            if [[ "$f" == *windows* ]]; then
              zip "$f.zip" "$f"
            else
              tar -czf "$f.tar.gz" "$f"
            fi
          done

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.{tar.gz,zip}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
